### ISSUE TITLE
[Feature Request] Add sound null safety support

### ISSUE THREAD

**Issue by arbile26** [rollbar/rollbar-flutter#10]
Please add sound null safety support.

**Comment by mgalgs** [comment]
Yeah, I'm getting the following Dart Analysis warning when importing the library:

```
info: The library 'package:rollbar_flutter/rollbar.dart' is legacy, and should not be imported into a null safe library. (import_of_legacy_library_into_null_safe at [sonlet_retailer] lib/main.dart:7)
```

**Comment by befirst** [comment]
@mgalgs you can use the next command to run the app: ` flutter run --no-sound-null-safety`

**Comment by mgalgs** [comment]
@befirst I know, but I can't ship my app like that

**Comment by mgalgs** [comment]
I think you should leave this open this until there's a release on pub.dev with sound null safety support. At the moment the only release on pub.dev is `0.1.0-beta`, which doesn't seem to have sound null safety.
