### ISSUE TITLE
Bump uuid to v4

### ISSUE THREAD

**Issue by antonengelhardt** [rollbar/rollbar-flutter#116]
Hello,
is it possible to bump `uuid` to `4.0.0`? One of our other dependencies needs this version. 
If not, does anyone know how i can have two dependencies which both rely on one sub-dependency but with different versions?
In our case: rollbart_dart depends on uuidv3 and analytics_flutter depends on uuidv4. 
Thanks.

**Comment by matux** [comment]
This should be fixed with https://github.com/rollbar/rollbar-flutter/pull/118. Thank you for reporting!
