### ISSUE TITLE
Null-safety migration ?

### ISSUE THREAD

**Issue by mehmettezcan** [rollbar/rollbar-flutter#17]
Do you plan migrate to null-safety?

**Comment by mgalgs** [comment]
Looks like the code is in (#10) but it hasn't been released yet :frowning_face:

**Comment by akornich** [comment]
@mgalgs , correct. I am in the process of getting my proper credentials to be able to publish it on pub.dev

**Comment by akornich** [comment]
it is published as v0.2.0-beta
