### ISSUE TITLE
rollbar_flutter version doesn't match

### ISSUE THREAD

**Issue by akterridealike** [rollbar/rollbar-flutter#21]
I am trying to flutter pub get of rollbar_flutter but facing the issues given  below.

![rollbar_isssue](https://user-images.githubusercontent.com/101618813/158569879-35abd974-2695-4205-af64-8cf7172c7721.PNG)
![flutter_version](https://user-images.githubusercontent.com/101618813/158569885-98db7afa-71e0-41b0-a2d8-899d62782042.PNG)

**Comment by akornich** [comment]
@akterridealike, could it be you have some other dependency package interfering with rollbar_flutter  or there is an issue with your Flutter package management environment?

I just upgraded my machine to Flutter 2.10.3:
![image](https://user-images.githubusercontent.com/1753993/158877456-e57a85b0-6b61-4708-8212-4e1ba203c7b6.png)

and was able to successfully add rollbar_flutter to a new Flutter test app:
![image](https://user-images.githubusercontent.com/1753993/158877844-0e760caa-fea7-4fbb-92d7-dd8826056283.png)

**Comment by mgalgs** [comment]
@akterridealike the only version released on pub.dev is `0.1.0-beta`. It should work if you change it from `0.1.0` to `0.1.0-beta` but `0.1.0-beta` still doesn't appear to have sound null safety support :frowning_face: 

https://pub.dev/packages/rollbar_flutter/versions

**Comment by akornich** [comment]
@akterridealike , please, try latest published v0.2.0-beta...
