### ISSUE TITLE
IOS Pods not be able to build in arm64 

### ISSUE THREAD

**Issue by EnriqueSanVic** [rollbar/rollbar-flutter#25]
The IOS Pods have a problem to compile in arm64, this platform its excluded in the Pods rollbar_flutter pods for compile the IOS build.

Log flutter run when create xcode build:

`Launching lib[/main.dart]() on iPhone 13 Pro Max in debug mode...
lib/main.dart:1
Xcode build done.                                           11,1s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-04-21 13:27:49.796 xcodebuild[51520:1566860] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-04-21 13:27:49.797 xcodebuild[51520:1566860] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	[/var/folders/3b/bz5ggf5x57qgm1vmv8p1zyhc0000gt/T/flutter_tools.djyeUm/flutter_ios_build_temp_dirrvNB3X/temporary_xcresult_bundle]()
    ld: warning: ignoring file [/Users/user/Desktop/folder/build/ios/Debug-iphonesimulator/Rollbar/Rollbar.framework/Rollbar](), file is universal (x86_64,i386) but does not contain the arm64 architecture: [/Users/user/Desktop/folder/build/ios/Debug-iphonesimulator/Rollbar/Rollbar.framework/Rollbar]()
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_Rollbar", referenced from:
          objc-class-ref in RollbarFlutterPlugin.o
         (maybe you meant: _OBJC_CLASS_$_RollbarMethodChannel, _OBJC_CLASS_$_RollbarFlutterPlugin )
      "_OBJC_CLASS_$_RollbarConfiguration", referenced from:
          objc-class-ref in RollbarFlutterPlugin.o
      "_OBJC_CLASS_$_RollbarTelemetry", referenced from:
          objc-class-ref in RollbarFlutterPlugin.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
2
    ld: interrupted
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    Result bundle written to path:
    	[/var/folders/3b/bz5ggf5x57qgm1vmv8p1zyhc0000gt/T/flutter_tools.djyeUm/flutter_ios_build_temp_dirrvNB3X/temporary_xcresult_bundle]()
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_Rollbar

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_RollbarConfiguration

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_RollbarTelemetry

Error (Xcode): Interrupted

Could not build the application for the simulator.
Error launching application on iPhone 13 Pro Max.`

**Comment by mgalgs** [comment]
I'm having the same problem when trying to build for the iOS simulator. Without the simulator I can't update the screenshots of my app for my app store listings 😢

**Comment by mgalgs** [comment]
Huh, I just updated the minimum deployment target to 12.0 and that seems to have dropped armv7, which has fixed this issue for me. :+1: 

![image](https://user-images.githubusercontent.com/152014/167520157-9436ae81-6e39-4f88-a433-3bdfc57e00a8.png)

**Comment by EnriqueSanVic** [comment]
I too had it set to the minimum deployment version on IOS 12 and it didn't work 🫤. 
If it can help you, my version of XCode is 13.3 (13E113) on a Mac with a 6 core Intel Core i5 processor (2019) on Monterey 12.3.1.
Thanks for your help.

**Comment by teivienn** [comment]
It helped me for react-native. Maybe this solution will help for flutter
https://github.com/aiba/react-native-m1/blob/main/README.md

**Comment by lailai0715** [comment]
Same issue here, any solution on this? Couldn't build my proj in iOS simulator

**Comment by tomgilder** [comment]
Yep, same here, possibly an M1 Mac issue as it's not compiling for arm64? I tried compiling with the latest code from Git.

**Comment by dhola-hardik** [comment]
It's working for me when I add `arm64` in Excluded Architectures.

Path: App -> Build Settings -> Architectures -> Excluded Architectures: set to arm64

![Screenshot at Nov 18 19-44-09](https://user-images.githubusercontent.com/83745421/202725510-0022359b-5679-4a8c-8c71-f1279e54c01c.png)
