### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by jamiepmullan** [rollbar/rollbar-flutter#37]
Hey, had some troubles with the current releases (0.2.0-beta) and believe some of the fixes have been merged in...
When is the next release coming?

**Comment by matux** [comment]
Hey @jamiepmullan, it's actually coming very soon! We've a PR in place that fixes most of the current issues we have in `0.2.0-beta`, including most of the ones I just added today in the Issues list.

I'll keep you posted!

**Comment by jamiepmullan** [comment]
Hey @matux - thanks for replying! I appreciate you can’t say when… but is it days, weeks or months? Got an app I need to integrate it with quite urgently!

**Comment by matux** [comment]
@jamiepmullan Less than 2 weeks, might be days if no more show-stopping issues pop up.

**Comment by matux** [comment]
@jamiepmullan The new version is out!
