### ISSUE TITLE
Excessive logging of Processing saved items

### ISSUE THREAD

**Issue by jjonte-cake** [rollbar/rollbar-flutter#89]
Upon adding Rollbar to my Flutter app, it spams my console with `[Rollbar] Processing saved items: no queued items in the file!`. I am unable to determine how to disable this.

**Comment by jesther-ai** [comment]
any workaround for this?

**Comment by jjonte-cake** [comment]
@jesther-ai Unfortunately, no - my workaround was to disable Rollbar in development.

```
if (settings.isDebug) {
    runApp(app);
  } else {
    final rollbarToken = settings.rollbarToken ?? '';
    final rollbarConfig = rollbar.Config(accessToken: rollbarToken, package: 'MyFlutterApp', includePlatformLogs: false);
    await rollbar.RollbarFlutter.run(rollbarConfig, () async => runApp(app));
  }
```

This is making question using Rollbar, a month later and not even an acknowledgement. Paid logging services are a dime a dozen.

**Comment by rollbar-bborsits** [comment]
Hey @jjonte-cake & @jesther-ai, Thanks for reporting this issue. We'll start investigating, and I'll get back to you with an update.

**Comment by matux** [comment]
This issue will be fixed in the new release of our Apple SDK, which is a dependency of the Flutter SDK we use to catch crashes and exceptions that occur natively.

As soon as that version is released and we update the Flutter SDK to use the new version, which should be soon, I'll comment here.
