### ISSUE TITLE
Unsetting an user causes invalid argument exception

### ISSUE THREAD

**Issue by rfuerst87** [rollbar/rollbar-flutter#91]
Calling `Rollbar.setUser(null)` causes

```
E/flutter ( 3075): Invalid argument (An Event must have either an error or a message.): event: Instance of 'Event'
E/flutter ( 3075): #0      _Body.from (package:rollbar_dart/src/wrangler/data_wrangler.dart:77:5)
E/flutter ( 3075): #1      _Data.from (package:rollbar_dart/src/wrangler/data_wrangler.dart:42:23)
E/flutter ( 3075): #2      DataWrangler.payload (package:rollbar_dart/src/wrangler/data_wrangler.dart:30:30)
E/flutter ( 3075): #3      _IsolatedNotifier$Isolate.run (package:rollbar_dart/src/notifier/isolated_notifier.dart:82:40)
```

Since the signature of `setUser` accepts `null` values, I assume this is the way to unset and user for example on logout. Is there another way I'm not aware of?

Otherwise I think this needs to be fixed in `AsyncNotifier.notify` and in `IsolateNotifier.run`. By the way those two methods seem to duplicate code.

**Comment by rollbar-bborsits** [comment]
Hey @rfuerst87, Thanks for reporting this issue. I'll check this with the devs and get back to you with an update.

**Comment by matux** [comment]
@rfuerst87 

A new release fixing this issue is out now @ pub.dev:
- https://pub.dev/packages/rollbar_dart
- https://pub.dev/packages/rollbar_flutter

I appreciate you reporting this issue, and if you find anything else, don't hesitate reporting, we'll do our best to take care of it asap.
